_schema: _schema
paths:
  uploads: public
  static: public
collections_config:
  src_content_posts:
    path: src/content/posts
    glob:
      -
    name: Posts
    icon: content_paste
    disable_url: false
    description: ''
    sort:
      key: date
      order:
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: ''
    name: Pages
    icon: wysiwyg
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Europe/Kiev
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
